### ISSUE TITLE
Invalid Input

### ISSUE THREAD

**Issue by SeLoRe** [niemtin007/Multiboot-Toolkit#1]
I got invalid input error with Multiboot Toolkit 2.1.4-beta.4 
![2017-05-07_12-06-01](https://cloud.githubusercontent.com/assets/10376753/25779330/169392e8-331e-11e7-8d18-5c8ee40dcdda.jpg)

**Comment by niemtin007** [comment]
Sorry, I fixed it, I need to fix some things else before the next release, please patience. Thanks.

**Comment by SeLoRe** [comment]
Thank you.
