### ISSUE TITLE
Add Simplified Chinese translations

### ISSUE THREAD

**Issue by a1ive** [niemtin007/Multiboot-Toolkit#1]
[zhcn.patch.gz](https://github.com/niemtin007/Multiboot-Toolkit/files/3614664/zhcn.patch.gz)

**Comment by niemtin007** [comment]
Hi A1ive,

Thank you for your contribution. I added your translation into Multiboot Toolkit. I have tried to support Unicode or China language before. But, the CMD shell is still VERY limited support for Unicode. So, the display of China language still missing a text and is replaced by "?" symbol.

If you have any solution to overcome this problem please let me know.

Thank in advance,
niemtin007.

**Comment by a1ive** [comment]
By default, windows batch only supports GB2312-80/GBK encoded Simplified Chinese characters and Big5 encoded Traditional Chinese characters.
To enable support for UTF-8 Chinese charaters, we should run `chcp 65001` first.

**Comment by a1ive** [comment]
![1](https://user-images.githubusercontent.com/10670106/65004775-24c41a80-d930-11e9-816c-f1d4c7050afe.png)
![2](https://user-images.githubusercontent.com/10670106/65004795-30afdc80-d930-11e9-8a31-6fcf20760855.png)

**Comment by niemtin007** [comment]
When I ran chcp 65001, windows command prompt cannot display language. What Simplified Chinese font we need to install first?

![image](https://user-images.githubusercontent.com/12592676/65005195-4241b600-d929-11e9-877a-a8c7700f366b.png)

**Comment by a1ive** [comment]
That's odd.
cmd can't display Vietnam for me, either (I've already installed the language pack).
![2](https://user-images.githubusercontent.com/10670106/65005828-cf8a0800-d933-11e9-99cd-297a76750d48.png)

**Comment by a1ive** [comment]
The default font for Windows in China is New Simsun (新宋体)
[simsun.ttc.gz](https://github.com/niemtin007/Multiboot-Toolkit/files/3618954/simsun.ttc.gz)

**Comment by niemtin007** [comment]
This font has installed in Window 10 by default. 

I found the solution for this case 
[Fixing Windows CMD Font Issue](https://syang.io/2018/10/22/Windows-CMD-Font-Issue.html)

When I changed the setting like this, it has worked perfectly for all language.
![CMDfont06](https://user-images.githubusercontent.com/12592676/65007378-27bf0b00-d930-11e9-93d3-27326fb39caa.png)

Demo:
![image](https://user-images.githubusercontent.com/12592676/65007460-74a2e180-d930-11e9-865d-68ec9709c2a4.png)

![image](https://user-images.githubusercontent.com/12592676/65007483-85ebee00-d930-11e9-96b9-db616852701d.png)

![image](https://user-images.githubusercontent.com/12592676/65007508-9c924500-d930-11e9-9ffd-0988daae408d.png)

One more thing I need to study: How can I activate this option automatic by batch script? Please let me know if you can resolve it.

Thank you for your kind support 👯‍♂

**Comment by a1ive** [comment]
It dosen't work for me.
![1](https://user-images.githubusercontent.com/10670106/65008496-21369080-d93c-11e9-9766-5af120347733.png)

**Comment by niemtin007** [comment]
Try to use the default English language pack of windows 10.

**Comment by a1ive** [comment]
The default language pack is English (United States)
![2](https://user-images.githubusercontent.com/10670106/65008800-1defd480-d93d-11e9-91c9-085e9ff21cef.png)
![1](https://user-images.githubusercontent.com/10670106/65008805-1fb99800-d93d-11e9-8fe8-122b3c6053c2.png)

**Comment by niemtin007** [comment]
Hello A1ive,

What font do you use in Windows Command Prompt by default?

Here is my font when I activate "Beta: Use Unicode UTF-8 for worldwide language support"
![image](https://user-images.githubusercontent.com/12592676/65034861-0bdc5900-d972-11e9-8d72-a4b9681754a5.png)

I found another way to fix china language in my system without activating "Beta: Use Unicode UTF-8..." is change font to Nsimsun
![image](https://user-images.githubusercontent.com/12592676/65035684-ff590000-d973-11e9-8e12-16a30c2f60e2.png)

But it's the cause of Vietnamese font error:
![image](https://user-images.githubusercontent.com/12592676/65035820-58c12f00-d974-11e9-928e-3df9d3ada95f.png)

I think the best way to activate china font in default English system is still activating "Beta: Use Unicode UTF-8..."

**Comment by a1ive** [comment]
default font: Consolas
default code page: 65001 (UTF-8)
![1](https://user-images.githubusercontent.com/10670106/65040978-47821d80-d988-11e9-88b7-cbc8213b4969.png)
chose Vietnamese (ok):
font: Consolas
code page: 65001 (UTF-8)
![3](https://user-images.githubusercontent.com/10670106/65041044-67b1dc80-d988-11e9-8090-4be8cd8189aa.png)
chose Chinese (error):
font: NSimsun
code page: 936 (GBK)  why??
![2](https://user-images.githubusercontent.com/10670106/65041153-a21b7980-d988-11e9-9360-27b25efddab2.png)

**Comment by niemtin007** [comment]
Did you clone the newest build to test? I have set up code page 65001 by default for all languages already.

![Capture2](https://user-images.githubusercontent.com/12592676/65048679-b4001b00-d98e-11e9-820c-36e2ed07df6b.PNG)

**Comment by a1ive** [comment]
After `git pull`, all languages are fine.
