### ISSUE TITLE
How to remove an installed iso image/module ?

### ISSUE THREAD

**Issue by cristian-ciobanu** [niemtin007/Multiboot-Toolkit#10]
I have installed an WinPE recovery image and I want to remove it and load another image instead of it.
Is this possible in this version 2.3.2 ?

**Comment by niemtin007** [comment]
Removing a module is fairly easy, except special ISO only works on hidden partition like:  Bitdefender, Fedora, Network Security Toolkit... All modules put on the MULTIBOOT partition. You just delete it on your USB/HDD device.

In your case, normally all PE modules have installed in the "WIM" folder. You just access to this directory and delete it.

P/s:  there is no change in the way to integrate modules.
