### ISSUE TITLE
Mất mục khởi chạy SYS Linux

### ISSUE THREAD

**Issue by tran4774** [niemtin007/Multiboot-Toolkit#14]
Em bị mất menu này, có cách nào khắc phục không ạ???
![image](https://user-images.githubusercontent.com/59108692/86621994-5b674080-bfe9-11ea-983f-6106edff9d9a.png)

**Comment by tran4774** [comment]
Em boot ở mode legacy ad ạ

**Comment by niemtin007** [comment]
Cái đấy là Grub2 File-Manager chứ nhỉ. Menu Syslinux ở gần dưới cùng ấy. Để cài lại GrubFM bạn dùng tùy chọn bên dưới.

![image](https://user-images.githubusercontent.com/12592676/87035017-e7a87c00-c212-11ea-85db-fd57490bf65c.png)

**Comment by tran4774** [comment]
Ko phải ad ơi, em mất cái SYS linux cơ. Cái hình em chụp là nó biến mất cái menu đó luôn

**Comment by niemtin007** [comment]
Nếu có thời gian rảnh mình dự định sẽ tách Syslinux bootloader ra như một tùy chọn để cài đặt, hiện tại bootloader này ít được sử dụng trên hầu hết các bản phân phối linux.
