### ISSUE TITLE
Pl Add Opencore Bootloader

### ISSUE THREAD

**Issue by ghost** [niemtin007/Multiboot-Toolkit#17]
It will be great if Opencore Bootloader is also added to MultiBoot Toolkit as its found a great bootloader to boot & install macOS on Intel or Amd Hardware in a very easy way.

**Comment by niemtin007** [comment]
I've thought about it before. But it is the part of Hackintosh. I think I haven't enough time to support Hackintosh if I integrating it into the Multiboot Toolkit.
