### ISSUE TITLE
batch file line ending problems

### ISSUE THREAD

**Issue by a1ive** [niemtin007/Multiboot-Toolkit#3]
All batch files in the repository have `LF` line endings, and therefore downloaded zip file has problems.
Batch files should have `CR LF` line endings.
https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings
https://help.github.com/en/articles/configuring-git-to-handle-line-endings
https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration

**Comment by niemtin007** [comment]
Hi a1ive,

The download ZIP file issue was fixed after adding a .gitattributes file.

Thank you for your kind support.
