### ISSUE TITLE
Grub2 File Manager Update

### ISSUE THREAD

**Issue by farukgkc** [niemtin007/Multiboot-Toolkit#5]
Hello my friend

When you update Grub2 File Manager, you are using source files. However, it may be problematic because it may be in the test version.

You can download and use the release version with the following batch script codes.

Good work
 
By_FaRuK - TNCTR

```
@echo off
cd /d "%~dp0"
set tempfilename=g2fmtemp.log
wget.exe -O %tempfilename%  https://github.com/a1ive/grub2-filemanager/releases >nul
for /f "tokens=1,6 delims=/" %%a in ('type "%tempfilename%" ^| findstr /i "releases/tag.*.</a>" ^| find /n /v "" ^| find "[1]"') do (
set "name=%%b" )
set "version=%name:~8,6%"
set "url=https://github.com/a1ive/grub2-filemanager/releases/download/%version%/grubfm-tr_TR.7z"
cls
wget.exe -O g2fm.7z %url% >nul
del %tempfilename% >nul
del .wget-hsts /s /q /f >nul
if exist g2fm ( rd /s /q g2fm >nul )
mkdir g2fm
7za.exe x "g2fm.7z" -o"g2fm" -aoa -y >nul
del g2fm.7z /s /q /f >nul
```

**Comment by niemtin007** [comment]
Hello there,

Thank you for your solution.

I used to think about it but A1live release too much distribute version each language. It's hard to change the language on Multiboot Toolkit without downloading other language versions. So, I integrated the grub2 file-manager from source files. I will add your suggestion as another option if you want.

Currently, you can download the stable release (such as grubfm-tr_TR.7z), put it in the "Modules" folder and installing it like a module.

(the issue can be fixed when I update the new grub2 pack from A1ive. But now I'm quite busy, sorry)
