### ISSUE TITLE
how can i use multiboot toolkit for install windows

### ISSUE THREAD

**Issue by phuongdm1987** [niemtin007/Multiboot-Toolkit#6]
I want add iso windows 10 to usb multiboot, please help, thanks!

**Comment by niemtin007** [comment]
Hi there,

It's effortless. Just copy Windows ISO file to "ISO" folder on the Multiboot device. 

![copy Windows ISO](https://user-images.githubusercontent.com/12592676/79067666-41b8a480-7ceb-11ea-86d2-7481d78aa0d4.png)


Then run it via "Install Windows From ISO files" menu on Grub2 bootloader (UEFI + Legacy BIOS Mode) 

![How to run Windows ISO](https://user-images.githubusercontent.com/12592676/79067823-82fd8400-7cec-11ea-8ab5-45dda586a4f4.png)


Or "winsetupfmx64.efi" from rEFInd (UEFI Mode Only).

![open Windows Installer menu from rEFInd](https://user-images.githubusercontent.com/12592676/79067882-f43d3700-7cec-11ea-8902-4c145fc21fe7.png)


If you have met any problem, please update to the last version of Grub File Manager (A1ive), try to use it to search and mount Windows ISO file to install.

![How to Install Windows from ISO via grubfm](https://user-images.githubusercontent.com/12592676/79068280-edfc8a00-7cef-11ea-8dc1-534c9edf1459.png)

**Comment by phuongdm1987** [comment]
Thanks,
It works.

Vào 19:06, CN, 12 Th4, 2020 niemtin007 <notifications@github.com> đã viết:
