### ISSUE TITLE
Mình tạo USB Multiboot 2.3.1 nhưng có tận 3 phân vùng?

### ISSUE THREAD

**Issue by oldman20** [niemtin007/Multiboot-Toolkit#7]
![Screen Shot 2020-05-01 at 13 02 57](https://user-images.githubusercontent.com/39668756/80785936-3b13a380-8bac-11ea-90b4-0a37afb1575c.png)
Không giống như các HD thì chỉ có 2 phân vùng
vậy nên chép các file iso và các module ntn vậy bạn?
thanks!

**Comment by niemtin007** [comment]
Khi cài đặt ban đầu bạn chọn y (yes) cho tùy chọn " Create EFI Partition for Secure Boot" nên mới sinh thêm 1 phân vùng cho secure boot (M-ESP). Mặc định 2 phân vùng M-ESP và rEFInd được ẩn. Khuyên nên dùng bản mới nhất trên github 2.3.2 (dù beta nhưng ổn định và nhiều tính năng hơn).

Có vẻ USB của bạn chưa được tạo đúng cách vì phân vùng data mặc định tên MULTIBOOT và các module sẽ đặt mặc định trên phân vùng NTFS này.

**Comment by oldman20** [comment]
theo mình hiểu thì "Create EFI Partition for Secure Boot" tức là tạo thêm phân vùng để secure boot trên UEFI chứ nhỉ? vậy nên mình mới chọn là y (yes)
Còn nếu chọn là n (no) thì nó sẽ k tạo phân vùng EFI cho secure boot? Như vậy liệu USB có thể vừa boot Legacy vừa boot UEFI không bạn?

**Comment by niemtin007** [comment]
Một cách ngắn gọn gì bạn vẫn có thể boot vào UEFI bình thường với điều kiện tắt tùy chọn Secure Boot trong giao diện UEFI firmware (kiểu như BIOS ấy). Còn Legacy thì luôn được hỗ trợ và boot bình thường.

> Cụ thể thì tùy chọn secure boot có thể bật tắt thông qua UEFI firmware, mặc định các máy laptop khi mua nhà sản xuất sẽ bật nó làm mặc định. Mục đích thường ngăn tấn công thông qua boot trước khi máy khởi động vào hệ điều hành. (tham khảo thêm tại: https://www.linuxjournal.com/content/take-control-your-pc-uefi-secure-boot).
> 
> Tuy nhiên thời gian đầu việc này ngăn việc cài multi-system (nhiều hệ điều hành trên cùng một máy) rất khó khăn nếu như bật chức năng này (các bản phân phối Linux đều khó vượt qua khóa này do Microsoft phụ trách trong việc quản lý chữ ký hệ điều hành bên thứ 3). Do thời gian trước thì quan điểm của Microsoft thì hệ điều hành nguồn mở là rác nên dĩ nhiên phần cứng mới sử dụng chuẩn UEFI cũng một phần nhằm hạn chế phần nào sự phát triển của Linux.
> 
> Các công cụ boot gần như hầu hết đều phát triển trên các bootloader/ bootmanager mã nguồn mở như Grub2, rEFInd... được dùng hầu hết trong các bản phân phối Linux nên việc có được các chữ ký này cũng khá khó khăn. Nên tất nhiên công cụ boot vào chuẩn UEFI không thể hoạt động nếu như chế độ Secure boot này mở.
> 
> Tùy chọn tạo thêm phân vùng hỗ trợ boot vào Secure boot là tùy chọn thêm nếu như bạn không muốn tắt tùy chọn Secure Boot trên máy tính của bạn. Nhưng làm giới hạn tính năng của thiết bị boot là chỉ có thể boot thông qua WinPE. Mặc dù hiện tại nhiều developer tạo ra khóa vượt secure boot cho Grub2 bootloader như Shim và MOK Manager nhưng cũng khó hoạt động ổn định.
> 
> Vì vậy, hầu hết các bản boot đều khuyên tắt chế độ Secure Boot trong UEFI trước khi khởi động để sử dụng được đầy đủ các chức năng (Multiboot-Toolkit cũng như vậy).
> 
> Bạn chỉ nên chọn tùy chọn trên nếu như một số máy bị khóa BIOS không chỉnh được. Còn lại nên tắt cho đỡ phiền. 

Túm lại thì khi tạo boot nên tắt tùy chọn trên, trước khi boot máy chạy UEFI thì nên vào BIOS tắt tùy  chọn Secure Boot đi, cứu hộ xong thì bất lại cũng được.

**Comment by oldman20** [comment]
OK, got it. Thank bạn
