### ISSUE TITLE
Về tích hợp cài hackintosh

### ISSUE THREAD

**Issue by oldman20** [niemtin007/Multiboot-Toolkit#8]
Chào bạn, mình đọc trong features và changelog thấy đề cập đến việc tích hợp boot hackintosh installer, nhưng chưa hiểu rõ làm thế nào?
Supported Install Hackintosh - add all versions with only one bootable device
bạn có thể giải thích giúp mình đc k? cám ơn bạn nhiều
Thank vì project rất đáng giá, chúc bạn thành công và sức khoẻ!
Thêm 1 vấn đề mình muốn hỏi: trong list modules mình k thấy có UbuntuDDE hay POP OS, Bitdefender Recuse,... bạn có thể tích hợp vào trong phiên bản mới k? cám ơn bạn!

**Comment by niemtin007** [comment]
Sau khi thay đổi cấu trúc từ bản 2.3.0 thì có thể tích hợp thêm bộ cài hackintosh lên bản boot này nhưng cần thông qua tool phân vùng Paragon Partition Manager. Chỉ khuyên tích hợp lên HDD/SSD Boot không thích hợp với USB vì bản phân bộ cài hackintosh đã 5GB rồi.

Việc boot bộ cài sẽ được thông qua Clover Boot Manager. Nhưng giữa việc tích hợp là một chuyện còn cài Hackintosh là một chuyện, bạn cần có kỹ năng đọc thông số phần cứng tốt và phải có kiến thức hackintosh nhất định để cài thành công. 

Ban đầu tính viết hướng dẫn để giúp các bạn tích hợp và đẩy một số module hackintosh đã làm sẵn lên cho các bạn nhưng nghĩ kỹ thì mình không có thời gian support các bạn vì sẽ sinh ra thêm việc cho mình là hỗ trợ hackintosh (Chuỗi bài viết hướng dẫn cài hackintosh mang đủ rắc rối cho mình rồi vì hỗ trợ được cho tất cả các bạn thì mình chẳng còn thời gian đâu để làm gì cả, thông cảm giúp mình)

Nếu bạn thích thì bạn có thể làm thủ công bằng cách tạo một bộ cài hackintosh trên một chiếc USB theo phương pháp thông thường là Createinstallmedia, sau đó dùng Paragon Partition Manager để chép phân vùng chứa bộ cài hackintosh lên ổ HDD/SSD Boot của bạn là xong. Việc còn lại là cấu hình config của clover bootloader và bổ sung kext custom (DSDT/SSDT nếu cần) để có thể boot và cài Hackintosh thành công.

Nếu có thời gian bạn có thể tìm hiểu thêm OpenCore Bootloader để cài hackintosh.

**Comment by niemtin007** [comment]
Về vấn đề các ISO linux hay đĩa Rescue Boot thì Các distro liên quan đến Ubuntu có thể boot bình thường, bạn chỉ việc copy vào folder ISO trên phân vùng MULTIBOOT. Boot thông qua menu Linux trên grub2 hoặc boot ISO thông qua trình quản lý nâng cao Grub2 File Manager do A1ive phát triển.

Riêng Bitdefender thì chỉ chạy được trên phân vùng FAT32, khi tạo bộ cài phần tùy chỉnh phân vùng bạn cần tạo thêm không gian cho nó. Bitdefender.iso cần đặt vào Modules folder và chạy Module Installer để nó tự động chép file và phân vùng ẩn.

Do không có thời gian nên mình chưa kiểm tra được các bản update sau này có thay đổi gì không, cũng có thể vài distro thay đổi cấu trúc nên không boot được. Cái này thì bạn nào tích hợp lỗi báo mình thì mình mới support mà fix, cũng không có thời gian kiểm tra hết mấy trăm distro được.

**Comment by oldman20** [comment]
> Sau khi thay đổi cấu trúc từ bản 2.3.0 thì có thể tích hợp thêm bộ cài hackintosh lên bản boot này nhưng cần thông qua tool phân vùng Paragon Partition Manager. Chỉ khuyên tích hợp lên HDD/SSD Boot không thích hợp với USB vì bản phân bộ cài hackintosh đã 5GB rồi.
> 
> Việc boot bộ cài sẽ được thông qua Clover Boot Manager. Nhưng giữa việc tích hợp là một chuyện còn cài Hackintosh là một chuyện, bạn cần có kỹ năng đọc thông số phần cứng tốt và phải có kiến thức hackintosh nhất định để cài thành công.
> 
> Ban đầu tính viết hướng dẫn để giúp các bạn tích hợp và đẩy một số module hackintosh đã làm sẵn lên cho các bạn nhưng nghĩ kỹ thì mình không có thời gian support các bạn vì sẽ sinh ra thêm việc cho mình là hỗ trợ hackintosh (Chuỗi bài viết hướng dẫn cài hackintosh mang đủ rắc rối cho mình rồi vì hỗ trợ được cho tất cả các bạn thì mình chẳng còn thời gian đâu để làm gì cả, thông cảm giúp mình)
> 
> Nếu bạn thích thì bạn có thể làm thủ công bằng cách tạo một bộ cài hackintosh trên một chiếc USB theo phương pháp thông thường là Createinstallmedia, sau đó dùng Paragon Partition Manager để chép phân vùng chứa bộ cài hackintosh lên ổ HDD/SSD Boot của bạn là xong. Việc còn lại là cấu hình config của clover bootloader và bổ sung kext custom (DSDT/SSDT nếu cần) để có thể boot và cài Hackintosh thành công.
> 
> Nếu có thời gian bạn có thể tìm hiểu thêm OpenCore Bootloader để cài hackintosh.

hi thank bạn nhiệt tình trả lời mình. Thực ra mình cũng biết chút ít về OSX86, lâu nay máy chính mình sử dụng vẫn là hackintosh, windows lâu rồi không cài trực tiếp mà chạy trên virtualbox :)
Như bạn thấy ảnh dưới mình đang sử dụng hackintosh chạy win10 trên virtualbox để tạo USB Multiboot mà! 
Nên việc chính mình muốn hỏi bạn là cách tích hợp thôi bạn ạ. Không biết bạn có nghe về tool AIOBoot cũng của người Việt mình làm không, trước đây mình thường xuyên dùng nó, nhưng có vẻ tác giả đã ngưng support và phát triển nó nên mình tìm lại trên vnz và đang thử trải nghiệm Multiboot Toolkit này của bạn, đa năng hơn rất nhiều và quan trọng là được deverloper support đều 👍 
Trong tool AIOBoot có tích hợp phần mount ảnh phân vùng, mình thường tạo mới bộ cài mac mỗi khi ra phiên bản macOS mới rồi tạo ảnh phân vùng bằng Disk trong Ubuntu Gnome (như ảnh là file Installer macOS Catalina 10.15.4 USB.hfs) sau đó sử dụng PartIMGMapper.exe để mount file ảnh ra USB nhưng không được cơ động vì khi mount xong nếu muốn sd USB bắt buộc phải unmount , nên việc có thể tạo đc file ảnh của phân vùng mac install mà k phải làm lại USB Multiboot rất có ý nghĩa với mình
![Screen Shot 2020-05-01 at 22 13 21](https://user-images.githubusercontent.com/39668756/80816081-0d088080-8bf9-11ea-8870-246ab1289314.png)
Theo như bạn HD thì mình dùng Paragon Partition sẽ tạo ra 1 phân vùng riêng cho cài hackintosh phải k bạn? Liệu nếu split phân vùng MULTIBOOT (NTFS) ra 1 khoảng đủ để tạo 1 partition làm nơi cài macOS thì hệ thống multiboot có bị ảnh hưởng k bạn? Nếu k vấn đề thì mình nghĩ clover bootloader có thể vẫn nhận đc macOS installer

**Comment by oldman20** [comment]
> Ban đầu tính viết hướng dẫn để giúp các bạn tích hợp và đẩy một số module hackintosh đã làm sẵn lên cho các bạn nhưng nghĩ kỹ thì mình không có thời gian support các bạn vì sẽ sinh ra thêm việc cho mình là hỗ trợ hackintosh (Chuỗi bài viết hướng dẫn cài hackintosh mang đủ rắc rối cho mình rồi vì hỗ trợ được cho tất cả các bạn thì mình chẳng còn thời gian đâu để làm gì cả, thông cảm giúp mình)
>
Bạn có thể gợi ý cho mình về vấn đề này k? Hiện mình đang sử dụng ổn định hackintosh nên sẽ k có rắc rối cho bạn lắm đâu :)

> Nếu bạn thích thì bạn có thể làm thủ công bằng cách tạo một bộ cài hackintosh trên một chiếc USB theo phương pháp thông thường là Createinstallmedia, sau đó dùng Paragon Partition Manager để chép phân vùng chứa bộ cài hackintosh lên ổ HDD/SSD Boot của bạn là xong. Việc còn lại là cấu hình config của clover bootloader và bổ sung kext custom (DSDT/SSDT nếu cần) để có thể boot và cài Hackintosh thành công.
> 
Mình chưa rõ cách tiến hành, bạn có thể support rõ hơn về việc sd Paragon để chép pv ntn k? (có vẻ hơi thiên về kiến thức cơ bản :(
> Nếu có thời gian bạn có thể tìm hiểu thêm OpenCore Bootloader để cài hackintosh.

Hiện mình cũng bắt đầu thử tìm hiểu về OpenCore để so sánh bạn ạ!
Chúc bạn buổi tối vui vẻ

**Comment by oldman20** [comment]
> Về vấn đề các ISO linux hay đĩa Rescue Boot thì Các distro liên quan đến Ubuntu có thể boot bình thường, bạn chỉ việc copy vào folder ISO trên phân vùng MULTIBOOT. Boot thông qua menu Linux trên grub2 hoặc boot ISO thông qua trình quản lý nâng cao Grub2 File Manager do A1ive phát triển.
> 
Thank bạn nhiều, về modules tích hợp thì khi nhìn vào file excel [Modules List for Multiboot Toolkit ](https://docs.google.com/spreadsheets/d/1HzW6t3Rh_8_BnT8Ddawe1epwrMdVzvmRAjtN3qX-G9k/edit#gid=0) mục **patch**, mình cũng k hiểu 1 cách đúng đắn như ý bạn nói được, ví dụ việc tích hợp **ESET** thì phải là copy folder **casper** theo đường dẫn rồi đổi tên là **ESET** thì mới sử dụng được ( mình có đọc [ở đây](https://chiasemaytinhtucoban.com/cuu-ho-may-tinh/tu-tao-mot-dia-usb-multiboot-da-nang-bang-cong-cu-multiboot-toolkit-moi-nhat-2019-phan-6-tich-hop-cac-bo-cong-cu-cuu-ho-diet-virut-mien-phi-pho-bien-tot-nhat.html) thì hd vậy! Nhưng trước khi đọc ở đấy thì làm theo như file excel kia thì ko được?
Nên chăng thêm 1 column ghi chú sẽ copy hay rename gì bạn nhỉ?

> Riêng Bitdefender thì chỉ chạy được trên phân vùng FAT32, khi tạo bộ cài phần tùy chỉnh phân vùng bạn cần tạo thêm không gian cho nó. Bitdefender.iso cần đặt vào Modules folder và chạy Module Installer để nó tự động chép file và phân vùng ẩn.
> 
Điều này mình đã biết và đã sử dụng cách này trên AIOBoot rồi bạn ạ. Cho mình hỏi hơi căn bản chút là có quy định phải đặt các file iso hay folder nào vào USB trước rồi mới chạy tool hay miễn là đặt chung với folder chứa file batch thực thi bạn nhỉ?

> Do không có thời gian nên mình chưa kiểm tra được các bản update sau này có thay đổi gì không, cũng có thể vài distro thay đổi cấu trúc nên không boot được. Cái này thì bạn nào tích hợp lỗi báo mình thì mình mới support mà fix, cũng không có thời gian kiểm tra hết mấy trăm distro được.

Hi nhất trí điều này, được Dev support nhiệt tình là nhất rồi :)

**Comment by niemtin007** [comment]
> Theo như bạn HD thì mình dùng Paragon Partition sẽ tạo ra 1 phân vùng riêng cho cài hackintosh phải k bạn? Liệu nếu split phân vùng MULTIBOOT (NTFS) ra 1 khoảng đủ để tạo 1 partition làm nơi cài macOS thì hệ thống multiboot có bị ảnh hưởng k bạn? Nếu k vấn đề thì mình nghĩ clover bootloader có thể vẫn nhận đc macOS installer

Phân vùng Multiboot không bị ảnh hưởng gì khi nới rộng hoặc thu nhỏ phân vùng phía bên phải. Bạn có thể chia nhỏ phân vùng Multiboot ra nhiều phân vùng con để ghi nhiều phân vùng cài MacOS được miễn đừng can thiệp các phân vùng phía trước là được.

> Mình chưa rõ cách tiến hành, bạn có thể support rõ hơn về việc sd Paragon để chép pv ntn k? (có vẻ hơi thiên về kiến thức cơ bản :(

Nếu bạn đã cài tốt Hackintosh thì cũng dễ hiểu thôi, xem hình dưới:

![Copy Partition Install MacOS](https://user-images.githubusercontent.com/12592676/80862464-92467080-8c9f-11ea-8e9c-75743beb41d2.png)

![Cách boot vào bộ cài hackintosh](https://user-images.githubusercontent.com/12592676/80862475-aab68b00-8c9f-11ea-9f56-1b916cfd9725.png)

-------------------

Riêng việc tích hợp Module thì đâu cần phải quan tâm đường dẫn trên thiết bị boot làm gì. Multiboot-Toolkit đã giúp tích hợp tự động bằng cách bỏ các ISO vào như mục Modules. Chạy script với tùy chọn thứ 2 là tích hợp Module, tool sẽ tự động phân loại và copy các module vào đúng thư mục trên thiết bị boot.

P/s: Bitdefender hình như bản mới đều bị lỗi trên hầu hết các tool. Eset cũng tốt nhưng build trên nền Linux cũ chỉ support tốt cho Legacy BIOS Mode. Nên dùng Kaspersky để được hỗ trợ tốt cho cả UEFI lẫn Legacy BIOS.

**Comment by oldman20** [comment]
cám ơn bạn nhiều, mình có dư 1 HDD box 160Gb nên có lẽ sẽ tích hợp luôn full bộ iso vs hackintosh install :). Nếu vậy thì tạo USB Multiboot toolkit xong mình split luôn phân vùng MULTIBOOT ra 1 par để create installmedia mac luôn lên đấy cho tiện hơn nhỉ? Nếu sd GPT cho HDD Box thì có vấn đề về tương thích nếu boot trên Legacy k bạn?
Bitdefender mình cũng thấy vậy, trc bản cũ thì tích hợp đc nhưng bản mới toàn lỗi boot

**Comment by oldman20** [comment]
> Riêng việc tích hợp Module thì đâu cần phải quan tâm đường dẫn trên thiết bị boot làm gì. Multiboot-Toolkit đã giúp tích hợp tự động bằng cách bỏ các ISO vào như mục Modules. Chạy script với tùy chọn thứ 2 là tích hợp Module, tool sẽ tự động phân loại và copy các module vào đúng thư mục trên thiết bị boot.

Như vậy mình k cần quan tâm đường dẫn, cần tích hợp thêm iso hay các tool gì ( miễn là Multiboot Toolkit support, tất nhiên) thì chỉ cần bỏ vào folder **Modules** rồi chạy script tích hợp là đc đúng k bạn?

**Comment by niemtin007** [comment]
> Nếu vậy thì tạo USB Multiboot toolkit xong mình split luôn phân vùng MULTIBOOT ra 1 par để create installmedia mac luôn lên đấy cho tiện hơn nhỉ? Nếu sd GPT cho HDD Box thì có vấn đề về tương thích nếu boot trên Legacy k bạn?

Bạn thử tạo một phân vùng tầm hơn 5GB trên ổ cứng di động rồi thử format qua định dạng hfs+ và tích hợp trực tiếp từ MacOS xem. Theo lý thuyết thì sẽ ok. Có MacOS thì đỡ phải xài Paragon Disk Manager để copy phân vùng. (Lúc tìm hiểu cài hackintosh mình chưa làm Multiboot, giờ thì máy lưu data nhiều mình không cài hackintosh nữa nên không có máy test)

> Như vậy mình k cần quan tâm đường dẫn, cần tích hợp thêm iso hay các tool gì ( miễn là Multiboot Toolkit support, tất nhiên) thì chỉ cần bỏ vào folder Modules rồi chạy script tích hợp là đc đúng k bạn?

Uhm, mặc định tool đã có sẵn list được phân loại những distro đã test ok ở thời điểm build nên cứ ném toàn bộ iso bạn cần vào thư mục Modules nó sẽ tự động phân loại tích hợp toàn bộ các module một lượt thay vì phải chọn từng module tích hợp, chờ xong rồi lại chọn như các tool khác.
Riêng một số ISO Linux chưa được test tool không nhận biết được thì bạn cứ ném thẳng vào thư mục ISO trên phân vùng Multiboot, trong menu grub2 thử boot thông qua phương pháp partnew. Hoặc có thể sử dụng Grub2 File Manager để duyệt file và boot iso của bạn.

**Comment by oldman20** [comment]
ok bạn , mình sẽ test và báo kêt quả sau 
chúc buổi tối vui vẻ! :)
