### ISSUE TITLE
Về việc bị mất menu grub khi boot bằng efi

### ISSUE THREAD

**Issue by tran4774** [niemtin007/Multiboot-Toolkit#9]
Ad có cách nào giải quyết vấn đề trên không ạ?

**Comment by niemtin007** [comment]
Bạn thông tin rõ giúp mình.
1. Hiện có phải bản đang xài bản 2.3.2 mới nhất được clone https://github.com/niemtin007/Multiboot-Toolkit.git hoặc file zip https://github.com/niemtin007/Multiboot-Toolkit/archive/master.zip không?
2. Mất menu sau khi cài đặt ban đầu hay sau khi sử dụng một chức năng mở rộng nào đó như fix/update/change bootloader ... ?

**Comment by tran4774** [comment]
Em đang xài bản mới nhất và em bị sau khi cài đặt lại multiboot lên usb

**Comment by niemtin007** [comment]
Mình vừa cài đặt lại cho chiếc USB cả theo cả MBR và GPT đều vẫn hiện bình thường. Bạn chụp giúp mình hình menu boot ban đầu và toàn bộ file trong đường dẫn EFI\BOOT để mình xem thử.
